### ISSUE TITLE
Task timeout

### ISSUE THREAD

**Issue by boite** [droid-php/droid#10]
By default, Symfony Process sets an upper bound on process execution time: `$timeout` is set to 60s.  Exceptions thrown because the runtime of a task exceeded this limit were encountered while testing modules, particularly when installing platform packages with apt-get.

Most tasks should complete in well under 60s, but it should be possible for a Task to declare a longer max execution time.

Symfony Process also allows for unlimited execution time and it might be useful to allow Tasks to run unlimited too - I can't immediately think of a use case for this.

Suggested solution:

```
Tasks:
  - name: "Do a thing for a long time."
    command: "some:command"
    max_runtime: 300 # seconds; or 0 for unlimited; not set == default (60s)
```
