### ISSUE TITLE
Merging variables recursively

### ISSUE THREAD

**Issue by boite** [droid-php/droid#11]
At present, top level Project.variables override top-level Module.variables. This is reasonable and allows a module to define defaults that can be overridden by the Projects in which the module is being used.

Top-level Target.variables override top level Project.variables. This is also reasonable and allows less-specific values to be defined in a Project while the Targets within can override the values with more-specific ones.

It should be possible for variables to follow this pattern at a deeper level so that, for example, a Project can override a subset of a Module's hierarchy of defaults:-

```
variables: # Project
    connect_params:
        host: "myhost.example.com"

variables: # Module (defaults)
    connect_params:
        host: "localhost"
        port: "31337"
```

At present, the above example would result in the loss of the `port` variable; that is, the Project.variables need to define all of the ones defined by the Module in order to override a subset of them.
