### ISSUE TITLE
Multiple uses of module with_items

### ISSUE THREAD

**Issue by boite** [droid-php/droid#12]
Modules that use `with_items` expect to find items under a specific variable, for example droid/user expects `mod_droid_user_users`.  This means that multiple uses of such a module within one project must each use the same set of items.

Consider a project in which we want to create different sets of user accounts on different machines:-

```
variables:
    mod_droid_user_users:
        - {username: some_user}
        - {username: some_other_user}
targets:
    make_apps:
        modules:
             - droid/user
    make_other_apps:
        modules:
             - droid/user
```

Currently both of these targets must create the same set of user accounts.

A solution to this could be to resolve the value of `with_items`, when the value is a variable name, relative to the name of the current target.  This would mean that the goal of the above example could be achieved with:

```
targets:
    make_apps:
        variables:
            mod_droid_user_users:
                - {username: some_user}
        modules:
             - droid/user
    make_other_apps:
        variables:
            mod_droid_user_users:
                - {username: some_other_user}
        modules:
             - droid/user
```
