### ISSUE TITLE
using with_items_filter throws notices on checking for undefined indexes

### ISSUE THREAD

**Issue by joostfaassen** [droid-php/droid#25]
Example from documentation:

```yml
target:
    make_website:
        variables:
            websites:
                - {path: "/var/www/mywebsite", ssl_cert: "/etc/ssl/mywebsite.cert"}
                - {path: "/var/www/myotherwebsite"}
        tasks:
            - name: "Install SSL certificate"
              ...
              with_items: "websites"
              with_items_filter: "item['ssl_cert']"
```

If `ssl_cert` is not defined in the items array (like the second website), PHP will throw the following error/warnings:

```sh
PHP Notice:  Undefined index: ssl_cert in vendor/symfony/expression-language/Node/GetAttrNode.php on line 94
PHP Stack trace:
PHP   1. {main}() vendor/droid/droid/bin/droid:0
PHP   2. Droid\Application->run() vendor/droid/droid/bin/droid:40
PHP   3. Symfony\Component\Console\Application->run() vendor/droid/droid/src/Application.php:113
PHP   4. Symfony\Component\Console\Application->doRun() vendor/symfony/console/Application.php:124
PHP   5. Symfony\Component\Console\Application->doRunCommand() vendor/symfony/console/Application.php:193
PHP   6. Symfony\Component\Console\Command\Command->run() vendor/symfony/console/Application.php:849
PHP   7. Droid\Command\BaseTargetCommand->execute() vendor/symfony/console/Command/Command.php:257
PHP   8. Droid\TaskRunner->runTarget() vendor/droid/droid/src/Command/BaseTargetCommand.php:54
PHP   9. Droid\TaskRunner->runTaskList() vendor/droid/droid/src/TaskRunner.php:193
PHP  10. Droid\TaskRunner->runTaskRemotely() vendor/droid/droid/src/TaskRunner.php:153
PHP  11. Droid\TaskRunner->getTaskHosts() vendor/droid/droid/src/TaskRunner.php:72
PHP  12. Symfony\Component\ExpressionLanguage\ExpressionLanguage->evaluate() vendor/droid/droid/src/TaskRunner.php:533
PHP  13. Symfony\Component\ExpressionLanguage\Node\BinaryNode->evaluate() vendor/symfony/expression-language/ExpressionLanguage.php:70
PHP  14. Symfony\Component\ExpressionLanguage\Node\GetAttrNode->evaluate() vendor/symfony/expression-language/Node/BinaryNode.php:90
```

WORKAROUND:

Add the following line to `bin/droid`:
```php
error_reporting(E_ALL & ~E_NOTICE);
```
