### ISSUE TITLE
Inferring inventory host properties from task variables

### ISSUE THREAD

**Issue by boite** [droid-php/droid#7]
Consider the following project variables used by a task that needs IP addresses of inventory hosts:-

```
# droid.yml
project:
  variables:
    nginx_upstreams:
      - name: some_apps
        strategy: ip_hash
        servers:
          - 192.0.2.1
          - 192.0.2.2
  tasks:
    - name: "Create upstreams"
      command: "fs:copy"
      arguments:
        src: "!{{ mod_path }}/assets/upstream.conf.template"
        dest: "/etc/nginx/conf.d/upstream-{{ item.name }}.conf"
      with_items: nginx_upstreams
```

where the list of IP addresses is used in the template:-

```
# assets/upstream.conf.template
upstream {{{ item.name }}} {
{{#each item.servers}}
    server {{{ . }}};
{{/each}}
...
```

The problem here is that if the IP addresses of inventory hosts should need to be changed then they must also be changed in these variables, adding to the maintenance burden.  Ideally they would be defined just once, in the droid inventory.

It would thus be useful to have some mechanism by which variables can reference the value of an inventory host property without explicitly giving the value. Perhaps something like:-

```
nginx_upstreams:
  - name: some_apps
    strategy: ip_hash
    servers:
      - inventory_group:
          name: app_servers
          property: private_ip
      - inventory_host:
          name: standalone_server
          property: public_ip
```

In this case, the `servers` property would still resolve to a list of IP addresses, one for each host in the `app_servers` group and one for the `standalone_server`.

This resolution could be done when the project is loaded, or better, immediately before the variables are fed to the task that needs them.

**Comment by boite** [comment]
Further use case:-

```
variables:
  module_nfs_server:
    exports:
      - path: "/share"
        common_opts: "rw,no_root_squash,no_subtree_check,fsid=0"
        clients:
          - name: 192.168.1.145
            opts: "sync"
          - name: 192.168.1.146
```

Here, we want to replace the `name` value, so we might do:-

```
clients:
  - name:
      inventory_host: {name: app0, property: private_ip}
    opts: "sync"
  - name:
      inventory_host: {name: app1, property: private_ip}
```

**Comment by boite** [comment]
This has been implemented in 32192cd.  The feature allows a reference to a single property of a single host:-

```
nginx_upstreams:
  - name: some_apps
    strategy: ip_hash
    servers:
      - %app_server1.public_ip%
      - %app_server2.public_ip%
```
